### ISSUE TITLE
Missing Pages

### ISSUE THREAD

**Issue by SkyBadPT** [InfinityWorldHI/RFID-Attendance-system-V2.0#3]
There are some missing pages, can they be added to the project?

**Comment by InfinityWorldHI** [comment]
What are the pages?

**Comment by SkyBadPT** [comment]
The register page, is the one that I remember now. But I'm not sure if there is more missing

**Comment by InfinityWorldHI** [comment]
But there was no register page from the beginning, You mean the reset password page?

**Comment by Miguelbg2020** [comment]
Hi,
I think the page is referring to is reset_pass.php i cant find it too.

I was trying to replicate your work, but when I try to login as admin, it always tells me wrong password. The password is correct, and I have created another admin in phpmyadmin with a different password and it keeps saying the same thing.

Could you help me with this problem?

**Comment by InfinityWorldHI** [comment]
Hello, Sorry for the late reply,
I haven't published the reset_pass.php page for public, since this page needs a public server with email service in order to allow resetting the password,
Regarding your question, the password must be stored in the database table in hash encryption, so you have either storing it using hash encryption or modifying the login page by removing the hashing part.

**Comment by 4xJ** [comment]
Hi! I have tried to change the password withe the MD5 but it still doesn't work. When I change in the SQL I got wrong password. Is the encryption MD5?
I have a public server for this project can I than use the reset_pass.php if you share it?

**Comment by stewert69** [comment]
https://github.com/stewert69/RFID-Attendance-system-V2.0
Added 3 files including reset_pass.php
There are only 2 lines in the file that need modified.
Enjoy.

**Comment by InfinityWorldHI** [comment]
I have published the missing pages as you all requested, Keep in mind updating the domain name inside the "reset_pass.php" file
